dist: xenial
language: python
python:
  - "3.7"

services:
  - xvfb

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov pytest-cov
  
install:
  - pip install .

before_script:
  - "export DISPLAY=:99.0"

script:
  - beamspy --help
  - pytest --cov=beamspy tests/

after_script:
  - codecov

